// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znzhyzjjqdwyteuahath.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpuemh5empqcWR3eXRldWFoYXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDM4MzUsImV4cCI6MjA3MzY3OTgzNX0.L9pjbR18v1xTItmGCqpINnWAKjU_hVs2YedWcCxojsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});